import 'package:flutter/material.dart';
import '../core/api/api_service.dart';
import '../core/theme/app_theme.dart';
import '../core/widgets/walking_loader.dart';

class GuestOtpScreen extends StatefulWidget {
  const GuestOtpScreen({super.key});

  @override
  State<GuestOtpScreen> createState() => _GuestOtpScreenState();
}

class _GuestOtpScreenState extends State<GuestOtpScreen> {
  final otpController = TextEditingController();
  bool loading = false;

  Future<void> verifyOtp() async {
    setState(() => loading = true);

    final response = await ApiService.post(
      "/visitors/verify-otp",
      {"otp": otpController.text.trim()},
    );

    setState(() => loading = false);

    if (response["visitor"] != null) {
      // ✅ OTP verified → redirect to visitors page
      Navigator.pushReplacementNamed(context, "/visitors");
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(response["message"] ?? "Invalid OTP"),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text("Guest OTP Entry"),
        centerTitle: true,
        backgroundColor: AppColors.primary,
        elevation: 0,
      ),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            const SizedBox(height: 40),
            const Icon(Icons.lock_open_rounded, size: 80, color: AppColors.primary),
            const SizedBox(height: 24),
            const Text(
              "Enter Guest OTP",
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: AppColors.textPrimary,
              ),
            ),
            const SizedBox(height: 8),
            const Text(
              "Ask the guest for the OTP generated by the resident.",
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 40),
            TextField(
              controller: otpController,
              keyboardType: TextInputType.number,
              textAlign: TextAlign.center,
              style: const TextStyle(fontSize: 24, letterSpacing: 8, fontWeight: FontWeight.bold),
              decoration: InputDecoration(
                hintText: "Enter OTP",
                hintStyle: const TextStyle(fontSize: 18, letterSpacing: 1, fontWeight: FontWeight.normal),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                filled: true,
                fillColor: Colors.white,
                contentPadding: const EdgeInsets.symmetric(vertical: 16),
              ),
            ),
            const SizedBox(height: 40),
            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton(
                onPressed: loading ? null : verifyOtp,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                child: loading
                    ? const SizedBox(
                        width: 24,
                        height: 24,
                        child: WalkingLoader(size: 24, color: Colors.white),
                      )
                    : const Text(
                        "VERIFY OTP",
                        style: TextStyle(fontSize: 16, color: Colors.white, letterSpacing: 1),
                      ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
