// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7SOLjoFX8V8BrkbRaKlq-EVDLOaMg9I',
    appId: '1:1000078003954:web:4ac515cb79c256e30c8a6b',
    messagingSenderId: '1000078003954',
    projectId: 'mobile-app-db450',
    authDomain: 'mobile-app-db450.firebaseapp.com',
    storageBucket: 'mobile-app-db450.firebasestorage.app',
    measurementId: 'G-MFQNG9DKFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKMq7gZXbF6MigAXfqunbT2Z-e0fxOjpg',
    appId: '1:1000078003954:android:efc2cd5b4c5e1a420c8a6b',
    messagingSenderId: '1000078003954',
    projectId: 'mobile-app-db450',
    storageBucket: 'mobile-app-db450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfarRcz4MtJcmAkXCbaTb8W0ddaliYEbA',
    appId: '1:1000078003954:ios:b792bc75bae9eaf60c8a6b',
    messagingSenderId: '1000078003954',
    projectId: 'mobile-app-db450',
    storageBucket: 'mobile-app-db450.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfarRcz4MtJcmAkXCbaTb8W0ddaliYEbA',
    appId: '1:1000078003954:ios:b792bc75bae9eaf60c8a6b',
    messagingSenderId: '1000078003954',
    projectId: 'mobile-app-db450',
    storageBucket: 'mobile-app-db450.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO7SOLjoFX8V8BrkbRaKlq-EVDLOaMg9I',
    appId: '1:1000078003954:web:21006c4f94bc4fe10c8a6b',
    messagingSenderId: '1000078003954',
    projectId: 'mobile-app-db450',
    authDomain: 'mobile-app-db450.firebaseapp.com',
    storageBucket: 'mobile-app-db450.firebasestorage.app',
    measurementId: 'G-YQ9BWT4NQN',
  );

}